application: translated-book
version: 3
runtime: python27
api_version: 1
threadsafe: true


automatic_scaling:
  min_idle_instances: automatic   # idle状態にあるインスタンスの最小値
  max_idle_instances: 1                 # idle状態にあるインスタンスの最大値
  min_pending_latency: 750ms  # リクエストを処理するまでに許される待ち時間の最小
  max_pending_latency: automatic


libraries:
- name: lxml
  version: latest

handlers:

- url: /_ah/(mapreduce|queue|warmup|start|stop).*
  script: translated_book.wsgi.application
  login: admin
  secure: always

- url: /_ah/internalupload.*
  script: translated_book.wsgi.application
  secure: always

# library static file
- url: /static/admin/
  static_dir: sitepackages/prod/django/contrib/admin/static/admin/
  secure: optional
  expiration: 30d


- url: /static/rest_framework/
  static_dir: sitepackages/prod/rest_framework/static/rest_framework/
  secure: optional
  expiration: 30d

- url: /static/rest_framework_swagger/
  static_dir: sitepackages/prod/rest_framework_swagger/static/rest_framework_swagger/
  secure: optional
  expiration: 30d

- url: /static
  static_dir: static/
  secure: always

# Set Django admin to be login:admin as well as Django's is_staff restriction
- url: /admin.*
  script: translated_book.wsgi.application
  secure: always
  login: admin

- url: /manage.*
  script: translated_book.wsgi.application
  secure: always
  login: admin

- url: /docs.*
  script: translated_book.wsgi.application
  login: admin
  secure: always


- url: /tasks/.*
  script: translated_book.wsgi.application
  login: admin
  secure: optional


- url: /.*
  script: translated_book.wsgi.application
  secure: always

skip_files:
  - ^manage\.py$
  - ^README\.md$
  - ^install_deps$
  - ^requirements/.*\.txt$
  - ^sitepackages/dev.*
  - ^.*\.(egg|dist)-info/.*$
  - node_modules/*

  # Defaults.
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
